[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
[context.production]
  [[context.production.headers]]
    for = "/*"
    [context.production.headers.values]
      X-Robots-Tag = "all"

[context.deploy-preview]
  [[context.deploy-preview.headers]]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex"
